FROM node:14-alpine
# Install git
RUN apk add --no-cache git
# Set working directory
WORKDIR /app
# Copy package.json
COPY package.json ./
# Install dependencies
RUN npm install
# Copy all files
COPY ./ ./
# Environment variables
ENV DB_HOST=mysql
ENV DB_NAME=database
ENV DB_USER=root
ENV DB_PASS=1Str0ngP@ssw0rd
ENV NODE_ENV=development
ENV NODE_ENV=development
ENV DB_HOST=mysql
ENV REDIS_HOST=redis:6379
# Port
EXPOSE 5000
# Run npm start
CMD ["npm", "run", "start:dev"]
