FROM node:14-alpine
# Install git
RUN apk add --no-cache git
# Set working directory
WORKDIR /app
# Copy package.json
COPY package.json ./
# Install dependencies
RUN npm install
# Copy all files
COPY ./ ./
# Run npm start
CMD ["npm", "run", "start:dev"]
