openapi: 3.0.0
info:
  title: Node Sequelize
  version: 0.0.1
  description: Node-Sequelize-OpenAPI is a sample project that demonstrates how to use Node.js, Sequelize, and OpenAPI to build a RESTful API.

servers:
  - url: http://localhost:3000/api/v1
    description: Internal server for development purposes only

paths:
  /items:
    get:
      responses:
        200:
          description: Returns a list of items
